// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(kanso_ffiFFI)
import kanso_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_kanso_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_kanso_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureKansoFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * The primary FFI object.  Wraps an owned Tokio runtime so every method can
 * block the calling thread while the async engine runs.
 *
 * Swift/Kotlin hold an `Arc<KansoEngine>`; UniFFI handles the reference count
 * on both sides.
 */
public protocol KansoEngineProtocol: AnyObject, Sendable {
    
    func createNote(notebookId: String, title: String, bodyMarkdown: String) throws  -> NoteDto
    
    func createNotebook(name: String, parentId: String?) throws  -> NotebookDto
    
    /**
     * Persist captured strokes as a sketch on a note. The native layer captures
     * raw stylus input and hands the normalized strokes here; the engine stores
     * the canonical CBOR document.
     */
    func createSketch(noteId: String, title: String?, strokes: [InkStroke]) throws  -> SketchDto
    
    func createTag(name: String) throws  -> TagDto
    
    func deleteNote(noteId: String) throws 
    
    func getNote(noteId: String) throws  -> NoteDto?
    
    func listNotebooks() throws  -> [NotebookDto]
    
    func listNotes(notebookId: String) throws  -> [NoteDto]
    
    func listSketches(noteId: String) throws  -> [SketchDto]
    
    func listTags() throws  -> [TagDto]
    
    func moveNote(noteId: String, notebookId: String) throws 
    
    /**
     * Render a sketch preview to PNG bytes (headless `tiny-skia`).
     */
    func renderSketchPreview(sketchId: String, width: UInt32, height: UInt32) throws  -> Data
    
    func searchNotes(query: String) throws  -> [NoteDto]
    
    func tagNote(noteId: String, tagId: String) throws 
    
    func updateNoteBody(noteId: String, bodyMarkdown: String) throws 
    
}
/**
 * The primary FFI object.  Wraps an owned Tokio runtime so every method can
 * block the calling thread while the async engine runs.
 *
 * Swift/Kotlin hold an `Arc<KansoEngine>`; UniFFI handles the reference count
 * on both sides.
 */
open class KansoEngine: KansoEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_kanso_ffi_fn_clone_kansoengine(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_kanso_ffi_fn_free_kansoengine(handle, $0) }
    }

    
    /**
     * Open (or create) a persistent database at `path`.
     */
public static func `open`(path: String)throws  -> KansoEngine  {
    return try  FfiConverterTypeKansoEngine_lift(try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_constructor_kansoengine_open(
        FfiConverterString.lower(path),$0
    )
})
}
    
    /**
     * Open a transient in-memory database (useful for tests / previews).
     */
public static func openInMemory()throws  -> KansoEngine  {
    return try  FfiConverterTypeKansoEngine_lift(try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_constructor_kansoengine_open_in_memory($0
    )
})
}
    

    
open func createNote(notebookId: String, title: String, bodyMarkdown: String)throws  -> NoteDto  {
    return try  FfiConverterTypeNoteDto_lift(try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_create_note(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(notebookId),
        FfiConverterString.lower(title),
        FfiConverterString.lower(bodyMarkdown),$0
    )
})
}
    
open func createNotebook(name: String, parentId: String?)throws  -> NotebookDto  {
    return try  FfiConverterTypeNotebookDto_lift(try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_create_notebook(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterOptionString.lower(parentId),$0
    )
})
}
    
    /**
     * Persist captured strokes as a sketch on a note. The native layer captures
     * raw stylus input and hands the normalized strokes here; the engine stores
     * the canonical CBOR document.
     */
open func createSketch(noteId: String, title: String?, strokes: [InkStroke])throws  -> SketchDto  {
    return try  FfiConverterTypeSketchDto_lift(try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_create_sketch(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(noteId),
        FfiConverterOptionString.lower(title),
        FfiConverterSequenceTypeInkStroke.lower(strokes),$0
    )
})
}
    
open func createTag(name: String)throws  -> TagDto  {
    return try  FfiConverterTypeTagDto_lift(try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_create_tag(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),$0
    )
})
}
    
open func deleteNote(noteId: String)throws   {try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_delete_note(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(noteId),$0
    )
}
}
    
open func getNote(noteId: String)throws  -> NoteDto?  {
    return try  FfiConverterOptionTypeNoteDto.lift(try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_get_note(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(noteId),$0
    )
})
}
    
open func listNotebooks()throws  -> [NotebookDto]  {
    return try  FfiConverterSequenceTypeNotebookDto.lift(try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_list_notebooks(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func listNotes(notebookId: String)throws  -> [NoteDto]  {
    return try  FfiConverterSequenceTypeNoteDto.lift(try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_list_notes(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(notebookId),$0
    )
})
}
    
open func listSketches(noteId: String)throws  -> [SketchDto]  {
    return try  FfiConverterSequenceTypeSketchDto.lift(try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_list_sketches(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(noteId),$0
    )
})
}
    
open func listTags()throws  -> [TagDto]  {
    return try  FfiConverterSequenceTypeTagDto.lift(try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_list_tags(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func moveNote(noteId: String, notebookId: String)throws   {try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_move_note(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(noteId),
        FfiConverterString.lower(notebookId),$0
    )
}
}
    
    /**
     * Render a sketch preview to PNG bytes (headless `tiny-skia`).
     */
open func renderSketchPreview(sketchId: String, width: UInt32, height: UInt32)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_render_sketch_preview(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(sketchId),
        FfiConverterUInt32.lower(width),
        FfiConverterUInt32.lower(height),$0
    )
})
}
    
open func searchNotes(query: String)throws  -> [NoteDto]  {
    return try  FfiConverterSequenceTypeNoteDto.lift(try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_search_notes(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),$0
    )
})
}
    
open func tagNote(noteId: String, tagId: String)throws   {try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_tag_note(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(noteId),
        FfiConverterString.lower(tagId),$0
    )
}
}
    
open func updateNoteBody(noteId: String, bodyMarkdown: String)throws   {try rustCallWithError(FfiConverterTypeKansoError_lift) {
    uniffi_kanso_ffi_fn_method_kansoengine_update_note_body(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(noteId),
        FfiConverterString.lower(bodyMarkdown),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKansoEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = KansoEngine

    public static func lift(_ handle: UInt64) throws -> KansoEngine {
        return KansoEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: KansoEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KansoEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: KansoEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKansoEngine_lift(_ handle: UInt64) throws -> KansoEngine {
    return try FfiConverterTypeKansoEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKansoEngine_lower(_ value: KansoEngine) -> UInt64 {
    return FfiConverterTypeKansoEngine.lower(value)
}




public struct ColorRgba: Equatable, Hashable {
    public var r: UInt8
    public var g: UInt8
    public var b: UInt8
    public var a: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(r: UInt8, g: UInt8, b: UInt8, a: UInt8) {
        self.r = r
        self.g = g
        self.b = b
        self.a = a
    }

    

    
}

#if compiler(>=6)
extension ColorRgba: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeColorRgba: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ColorRgba {
        return
            try ColorRgba(
                r: FfiConverterUInt8.read(from: &buf), 
                g: FfiConverterUInt8.read(from: &buf), 
                b: FfiConverterUInt8.read(from: &buf), 
                a: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: ColorRgba, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.r, into: &buf)
        FfiConverterUInt8.write(value.g, into: &buf)
        FfiConverterUInt8.write(value.b, into: &buf)
        FfiConverterUInt8.write(value.a, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeColorRgba_lift(_ buf: RustBuffer) throws -> ColorRgba {
    return try FfiConverterTypeColorRgba.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeColorRgba_lower(_ value: ColorRgba) -> RustBuffer {
    return FfiConverterTypeColorRgba.lower(value)
}


/**
 * One captured stylus sample. The native layer (PencilKit-free; raw
 * `UITouch`/`NSEvent`/`MotionEvent`) normalizes its input into these.
 */
public struct InkPoint: Equatable, Hashable {
    public var x: Float
    public var y: Float
    /**
     * 0.0–1.0 pen pressure; pass 1.0 for mouse/finger without force.
     */
    public var pressure: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x: Float, y: Float, 
        /**
         * 0.0–1.0 pen pressure; pass 1.0 for mouse/finger without force.
         */pressure: Float) {
        self.x = x
        self.y = y
        self.pressure = pressure
    }

    

    
}

#if compiler(>=6)
extension InkPoint: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeInkPoint: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> InkPoint {
        return
            try InkPoint(
                x: FfiConverterFloat.read(from: &buf), 
                y: FfiConverterFloat.read(from: &buf), 
                pressure: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: InkPoint, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.x, into: &buf)
        FfiConverterFloat.write(value.y, into: &buf)
        FfiConverterFloat.write(value.pressure, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInkPoint_lift(_ buf: RustBuffer) throws -> InkPoint {
    return try FfiConverterTypeInkPoint.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInkPoint_lower(_ value: InkPoint) -> RustBuffer {
    return FfiConverterTypeInkPoint.lower(value)
}


/**
 * One captured stroke: a point list plus styling.
 */
public struct InkStroke: Equatable, Hashable {
    public var points: [InkPoint]
    public var color: ColorRgba
    public var width: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(points: [InkPoint], color: ColorRgba, width: Float) {
        self.points = points
        self.color = color
        self.width = width
    }

    

    
}

#if compiler(>=6)
extension InkStroke: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeInkStroke: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> InkStroke {
        return
            try InkStroke(
                points: FfiConverterSequenceTypeInkPoint.read(from: &buf), 
                color: FfiConverterTypeColorRgba.read(from: &buf), 
                width: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: InkStroke, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeInkPoint.write(value.points, into: &buf)
        FfiConverterTypeColorRgba.write(value.color, into: &buf)
        FfiConverterFloat.write(value.width, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInkStroke_lift(_ buf: RustBuffer) throws -> InkStroke {
    return try FfiConverterTypeInkStroke.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInkStroke_lower(_ value: InkStroke) -> RustBuffer {
    return FfiConverterTypeInkStroke.lower(value)
}


/**
 * Flat representation of a note.
 *
 * `pinned` and `favorite` are booleans; the engine stores them as `i64`
 * (SQLite has no boolean type) so we convert on the way out.
 */
public struct NoteDto: Equatable, Hashable {
    public var id: String
    public var notebookId: String
    public var title: String
    public var bodyMarkdown: String
    public var createdAt: Int64
    public var updatedAt: Int64
    public var pinned: Bool
    public var favorite: Bool
    public var status: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, notebookId: String, title: String, bodyMarkdown: String, createdAt: Int64, updatedAt: Int64, pinned: Bool, favorite: Bool, status: String) {
        self.id = id
        self.notebookId = notebookId
        self.title = title
        self.bodyMarkdown = bodyMarkdown
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.pinned = pinned
        self.favorite = favorite
        self.status = status
    }

    

    
}

#if compiler(>=6)
extension NoteDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNoteDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NoteDto {
        return
            try NoteDto(
                id: FfiConverterString.read(from: &buf), 
                notebookId: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                bodyMarkdown: FfiConverterString.read(from: &buf), 
                createdAt: FfiConverterInt64.read(from: &buf), 
                updatedAt: FfiConverterInt64.read(from: &buf), 
                pinned: FfiConverterBool.read(from: &buf), 
                favorite: FfiConverterBool.read(from: &buf), 
                status: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: NoteDto, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.notebookId, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.bodyMarkdown, into: &buf)
        FfiConverterInt64.write(value.createdAt, into: &buf)
        FfiConverterInt64.write(value.updatedAt, into: &buf)
        FfiConverterBool.write(value.pinned, into: &buf)
        FfiConverterBool.write(value.favorite, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNoteDto_lift(_ buf: RustBuffer) throws -> NoteDto {
    return try FfiConverterTypeNoteDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNoteDto_lower(_ value: NoteDto) -> RustBuffer {
    return FfiConverterTypeNoteDto.lower(value)
}


/**
 * Flat representation of a notebook, safe to cross the FFI boundary.
 */
public struct NotebookDto: Equatable, Hashable {
    public var id: String
    public var name: String
    public var parentId: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, parentId: String?) {
        self.id = id
        self.name = name
        self.parentId = parentId
    }

    

    
}

#if compiler(>=6)
extension NotebookDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNotebookDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NotebookDto {
        return
            try NotebookDto(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                parentId: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: NotebookDto, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.parentId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNotebookDto_lift(_ buf: RustBuffer) throws -> NotebookDto {
    return try FfiConverterTypeNotebookDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNotebookDto_lower(_ value: NotebookDto) -> RustBuffer {
    return FfiConverterTypeNotebookDto.lower(value)
}


/**
 * Flat representation of a sketch.
 */
public struct SketchDto: Equatable, Hashable {
    public var id: String
    public var noteId: String
    public var title: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, noteId: String, title: String?) {
        self.id = id
        self.noteId = noteId
        self.title = title
    }

    

    
}

#if compiler(>=6)
extension SketchDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSketchDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SketchDto {
        return
            try SketchDto(
                id: FfiConverterString.read(from: &buf), 
                noteId: FfiConverterString.read(from: &buf), 
                title: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SketchDto, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.noteId, into: &buf)
        FfiConverterOptionString.write(value.title, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSketchDto_lift(_ buf: RustBuffer) throws -> SketchDto {
    return try FfiConverterTypeSketchDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSketchDto_lower(_ value: SketchDto) -> RustBuffer {
    return FfiConverterTypeSketchDto.lower(value)
}


/**
 * Flat representation of a tag.
 */
public struct TagDto: Equatable, Hashable {
    public var id: String
    public var name: String
    public var color: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, color: String?) {
        self.id = id
        self.name = name
        self.color = color
    }

    

    
}

#if compiler(>=6)
extension TagDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTagDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TagDto {
        return
            try TagDto(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                color: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: TagDto, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.color, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTagDto_lift(_ buf: RustBuffer) throws -> TagDto {
    return try FfiConverterTypeTagDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTagDto_lower(_ value: TagDto) -> RustBuffer {
    return FfiConverterTypeTagDto.lower(value)
}


public enum KansoError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Engine(message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension KansoError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKansoError: FfiConverterRustBuffer {
    typealias SwiftType = KansoError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KansoError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Engine(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: KansoError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Engine(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKansoError_lift(_ buf: RustBuffer) throws -> KansoError {
    return try FfiConverterTypeKansoError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKansoError_lower(_ value: KansoError) -> RustBuffer {
    return FfiConverterTypeKansoError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeNoteDto: FfiConverterRustBuffer {
    typealias SwiftType = NoteDto?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeNoteDto.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeNoteDto.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeInkPoint: FfiConverterRustBuffer {
    typealias SwiftType = [InkPoint]

    public static func write(_ value: [InkPoint], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeInkPoint.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [InkPoint] {
        let len: Int32 = try readInt(&buf)
        var seq = [InkPoint]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeInkPoint.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeInkStroke: FfiConverterRustBuffer {
    typealias SwiftType = [InkStroke]

    public static func write(_ value: [InkStroke], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeInkStroke.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [InkStroke] {
        let len: Int32 = try readInt(&buf)
        var seq = [InkStroke]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeInkStroke.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeNoteDto: FfiConverterRustBuffer {
    typealias SwiftType = [NoteDto]

    public static func write(_ value: [NoteDto], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeNoteDto.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [NoteDto] {
        let len: Int32 = try readInt(&buf)
        var seq = [NoteDto]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeNoteDto.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeNotebookDto: FfiConverterRustBuffer {
    typealias SwiftType = [NotebookDto]

    public static func write(_ value: [NotebookDto], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeNotebookDto.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [NotebookDto] {
        let len: Int32 = try readInt(&buf)
        var seq = [NotebookDto]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeNotebookDto.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSketchDto: FfiConverterRustBuffer {
    typealias SwiftType = [SketchDto]

    public static func write(_ value: [SketchDto], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSketchDto.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SketchDto] {
        let len: Int32 = try readInt(&buf)
        var seq = [SketchDto]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSketchDto.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTagDto: FfiConverterRustBuffer {
    typealias SwiftType = [TagDto]

    public static func write(_ value: [TagDto], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTagDto.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TagDto] {
        let len: Int32 = try readInt(&buf)
        var seq = [TagDto]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTagDto.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_kanso_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_create_note() != 19727) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_create_notebook() != 15109) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_create_sketch() != 47100) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_create_tag() != 30943) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_delete_note() != 61811) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_get_note() != 24197) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_list_notebooks() != 11176) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_list_notes() != 891) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_list_sketches() != 43733) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_list_tags() != 22735) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_move_note() != 2739) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_render_sketch_preview() != 15163) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_search_notes() != 37587) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_tag_note() != 32525) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_method_kansoengine_update_note_body() != 3144) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_constructor_kansoengine_open() != 2314) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kanso_ffi_checksum_constructor_kansoengine_open_in_memory() != 64353) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureKansoFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all